plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.0'
}

group = 'com.starrailhearing'
version = '0.1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa:4.1.0'
    implementation 'org.springframework.boot:spring-boot-starter-flyway:4.1.0'
    implementation 'org.springframework.boot:spring-boot-starter-jackson:4.1.0'
    implementation 'org.springframework.boot:spring-boot-starter-restclient:4.1.0'
    implementation 'org.springframework.boot:spring-boot-starter-security:4.1.0'
    implementation 'org.springframework.boot:spring-boot-starter-security-oauth2-client:4.1.0'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf:4.1.0'
    implementation 'org.springframework.boot:spring-boot-starter-validation:4.1.0'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc:4.1.0'
    implementation 'org.flywaydb:flyway-mysql:12.4.0'
    implementation 'org.yaml:snakeyaml:2.6'
    implementation 'com.twelvemonkeys.imageio:imageio-webp:3.12.0'

    developmentOnly 'org.springframework.boot:spring-boot-devtools:4.1.0'
    runtimeOnly 'com.mysql:mysql-connector-j:9.7.0'

    testImplementation 'org.springframework.boot:spring-boot-starter-test:4.1.0'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers:4.1.0'
    testImplementation 'org.springframework.security:spring-security-test:7.1.0'
    testImplementation platform('org.testcontainers:testcontainers-bom:1.20.6')
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:mysql'
    testRuntimeOnly 'com.h2database:h2:2.4.240'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:6.0.3'
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += ['-parameters', '-Xlint:deprecation']
}
