package com.starrailhearing.moderation.domain;

public enum ModerationActionType {
    WARNING,
    SUSPEND_1_DAY,
    SUSPEND_7_DAYS,
    SUSPEND_30_DAYS,
    SUSPEND_PERMANENT,
    RESTORE_WRITE,
    HIDE_COMMENT,
    RESTORE_COMMENT,
    ACTION_REPORT,
    DISMISS_REPORT,
    GRANT_BADGE,
    REVOKE_BADGE,
    APPROVE_TITLE,
    REJECT_TITLE,
    CREATE_VERSION,
    OPEN_VERSION,
    CLOSE_VERSION,
    CREATE_CHARACTER,
    UPDATE_CHARACTER,
    HIDE_CHARACTER,
    SHOW_CHARACTER,
    UPDATE_EXTERNAL_ALIAS
}
